// Copyright The gittuf Authors
// SPDX-License-Identifier: Apache-2.0

package attestations

import (
	"errors"

	"github.com/gittuf/gittuf/internal/rsl"
	"github.com/gittuf/gittuf/pkg/gitinterface"
)

const (
	Ref = "refs/gittuf/attestations"

	referenceAuthorizationsTreeEntryName = "reference-authorizations"

	githubPullRequestAttestationsTreeEntryName = "github-pull-requests"
	githubPullRequestApprovalSystemName        = "github"

	codeReviewApprovalAttestationsTreeEntryName = "code-review-approvals"
	codeReviewApprovalIndexTreeEntryName        = "review-index.json"

	initialCommitMessage = "Initial commit"
	defaultCommitMessage = "Update attestations"
)

var ErrAttestationsNotFound = errors.New("attestations not found")

// Attestations tracks all the attestations in a gittuf repository.
type Attestations struct {
	// referenceAuthorizations maps each authorized action to the blob ID of the
	// attestation. The key is a path of the form
	// `<ref-path>/<from-id>-<to-id>`, where `ref-path` is the absolute ref path
	// such as `refs/heads/main` and `from-id` and `to-id` determine how the ref
	// in question moved. For example, the key
	// `refs/heads/main/<commit-A>-<tree-B>` indicates the authorization is
	// for the action of moving `refs/heads/main` from `commit-A` to a commit
	// with `tree-B`.
	referenceAuthorizations map[string]gitinterface.Hash

	// githubPullRequestAttestations maps information about the GitHub pull
	// request for a commit and branch. The key is a path of the form
	// `<ref-path>/<commit-id>`, where `ref-path` is the absolute ref path, and
	// `commit-id` is the ID of the merged commit.
	githubPullRequestAttestations map[string]gitinterface.Hash

	// codeReviewApprovalAttestations stores the blob ID of a code review
	// approval attestation generated by or on behalf of a system like GitHub or
	// Gerrit for the change it applies to. The key is a path of the form
	// `<ref-path>/<from-id>-<to-id>/<system>`, where `ref-path` is the absolute
	// ref path such as `refs/heads/main` and `from-id` and `to-id` determine
	// how the ref in question moved. `<system>` identifies the code review
	// system in question. For example, the key
	// `refs/heads/main/<commit-A>-<tree-B>/github` indicates the approved
	// change updated `refs/heads/main` from `commit-A` to a commit with
	// `tree-B`, and that the approval originated on GitHub.
	codeReviewApprovalAttestations map[string]gitinterface.Hash

	// codeReviewApprovalIndex is stored in-memory. It maps a code review
	// system's approval ID to the gittuf identifier for a review,
	// `<ref-path>/<from-id>-<to-id>/<system>`. We need this because when a
	// review is dismissed, we need to unambiguously know what the review
	// applied to when it was first submitted, which we cannot do with the
	// information at the time of dismissal. This is serialized to the
	// attestations namespace as a special blob in the
	// codeReviewApprovalAttestations tree.
	codeReviewApprovalIndex map[string]string
}

// LoadCurrentAttestations inspects the repository's attestations namespace and
// loads the current attestations.
func LoadCurrentAttestations(repo *gitinterface.Repository) (*Attestations, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// LoadAttestationsForEntry loads the repository's attestations for a particular
// RSL entry for the attestations namespace.
func LoadAttestationsForEntry(repo *gitinterface.Repository, entry rsl.ReferenceUpdaterEntry) (*Attestations, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// This happens in the initial commit for the attestations namespace,
// where there are no entries in the tree yet.
// This is expected, and there is nothing more to check so return a zero Attestations state.

// Load the approval index that maps review IDs to the gittuf way of
// mapping the review to a change in the repository

// Commit writes the state of the attestations to the repository, creating a new
// commit with the changes made. An RSL entry is also recorded for the
// namespace.
func (a *Attestations) Commit(repo *gitinterface.Repository, commitMessage string, createRSLEntry, signCommit bool) error {
	_ = "STUB: not implemented"
	return nil
}

// Create a JSON blob for the approval index

// We must reset to original attestation commit if err != nil from here onwards.
